Repository synapsecns/sdk, pull requests merged in 2021-12, with the labels that each got.

#3 Merge dev into master
  src/abis/L2BridgeZap.json
  src/bridge/bridge.ts
  src/common/chainid.ts
  src/common/networks.ts
  src/common/swaptype.ts
  src/common/synapse_contracts.ts
  src/common/utils.ts
  src/contracts/gen/L2BridgeZap.ts
  src/contracts/gen/factories/L2BridgeZap__factory.ts
  src/index.ts
  src/rpcproviders/index.ts
  src/swappools/swappools.ts
  src/tokens/tokens.ts
  test/basic/Basic-test.ts
  test/bridge/SynapseBridge-test.ts
  test/helpers/index.ts
  tsconfig.json
Labels: enhancement

#7 Dev
  test/bridge/SynapseBridge-test.ts
  test/bridge/slippages-test.ts
Labels: enhancement, non-breaking, tests

#8 Env rpc uris
  package.json
  src/rpcproviders/index.ts
  src/rpcproviders/uris.ts
  test/basic/Env-test.ts
  test/basic/test_env.env
  yarn.lock
Labels: enhancement, non-breaking

#10 Update token addresses (and add new ones)
  src/tokens/tokens.ts
  test/bridge/SynapseBridge-test.ts
Labels: enhancement, non-breaking

#9 remove console.log in BridgeCard.js
  example/bridge/src/components/BridgeCard.js
  example/token_infos/.gitignore
  example/token_infos/package.json
  example/token_infos/public/favicon.ico
  example/token_infos/public/index.html
  example/token_infos/public/logo192.png
  example/token_infos/public/logo512.png
  example/token_infos/public/manifest.json
  example/token_infos/public/robots.txt
  example/token_infos/src/App.css
  example/token_infos/src/App.js
  example/token_infos/src/App.test.js
  example/token_infos/src/components/TokenDetails.js
  example/token_infos/src/index.css
  example/token_infos/src/index.js
  example/token_infos/src/logo.svg
  example/token_infos/src/reportWebVitals.js
  example/token_infos/src/setupTests.js
  example/token_infos/yarn.lock
Labels: enhancement, non-breaking
